import type { StockBundle } from "@/lib/stockData";
import type { FundamentalsTTM } from "@/lib/fmp";

export type ResearchBundle = StockBundle & {
  peerFundamentals: Record<string, FundamentalsTTM | null>;
};

export interface Lens {
  key: "business" | "forensic" | "valuation" | "bear";
  title: string;
  model: string;
  maxTokens: number;
  systemPrompt: string;
}

// Every lens must obey the data-only rule — it is the primary hallucination control.
const DATA_ONLY_RULE = `CRITICAL RULES:
- Reason ONLY from the JSON data provided in the user message. Do NOT use any knowledge about this company from your training data beyond what the JSON shows.
- If a field is null or missing, write "not available" — never estimate or recall a value.
- Cite concrete figures from the data when making claims.
- Write for a beginner investor: explain any finance term the first time you use it.
- Never give a buy/sell/hold recommendation.`;

export const LENSES: Lens[] = [
  {
    key: "business",
    title: "Business Analyst",
    model: "gpt-5.4",
    maxTokens: 1200,
    systemPrompt: `You are a business analyst explaining a company to a beginner investor.
From the data provided (especially the profile description, sector/industry, revenue, margins, and peers), explain in plain language: what this company actually does, how it makes money, how big it is, and whether the data suggests it has durable advantages (a "moat"). Be concrete and grounded.
${DATA_ONLY_RULE}`,
  },
  {
    key: "forensic",
    title: "Forensic Accountant",
    model: "gpt-5.4",
    maxTokens: 1200,
    systemPrompt: `You are a skeptical forensic accountant reviewing a company's financial statements for a beginner investor.
From the balance sheet, cash flow statement, income statement, and health ratios provided, assess: debt load and coverage, cash generation quality (operating cash flow vs net income), buybacks/dividends vs free cash flow, negative equity or shrinking retained earnings, and anything that looks stretched. Name specific red flags with figures, and also say clearly what looks healthy.
${DATA_ONLY_RULE}`,
  },
  {
    key: "valuation",
    title: "Valuation Analyst",
    model: "gpt-5.4",
    maxTokens: 1200,
    systemPrompt: `You are a valuation analyst writing for a beginner investor.
From the valuation multiples (P/E, PEG, P/S, P/FCF, EV/EBITDA, yields), the peer fundamentals provided, analyst price targets, and forward estimates, assess: how the market is pricing this company relative to its peers and its own growth expectations, and what level of growth appears already "priced in". Do not predict prices; describe what the current price implies.
${DATA_ONLY_RULE}`,
  },
  {
    key: "bear",
    title: "Short Seller",
    model: "gpt-5.4",
    maxTokens: 1200,
    systemPrompt: `You are an honest short seller building the strongest bear case, for a beginner investor's education.
From the data provided, argue the strongest honest case AGAINST owning this company: valuation risk, balance sheet risk, deteriorating trends, concentration, analyst optimism vs fundamentals. Steelman it — no strawmen, no exaggeration beyond what the data supports.
${DATA_ONLY_RULE}`,
  },
];

export const SYNTHESIS_MODEL = "gpt-5.4";
export const SYNTHESIS_MAX_TOKENS = 3000;

export const DISCLAIMER =
  "This report was generated by AI from public financial data for educational purposes only. It is not financial advice. Language models make mistakes — verify all figures independently before making any investment decision.";

export const RESEARCH_TIMEOUT_MS = 10 * 60 * 1000;

/** Maps a stale 'running' row to a presented 'failed' status (no reaper job). */
export function presentStatus(row: { status: string; created_at: string }): { status: string; error?: string } {
  if (row.status === "running" && Date.now() - new Date(row.created_at).getTime() > RESEARCH_TIMEOUT_MS) {
    return { status: "failed", error: "timed out" };
  }
  return { status: row.status };
}

/** One shared user prompt: the full data bundle as JSON. */
export function buildLensPrompt(bundle: ResearchBundle): string {
  return `Here is the complete financial data bundle for ${bundle.quote.symbol} (${bundle.quote.name}). Analyze it according to your role.

DATA (JSON):
${JSON.stringify(bundle, null, 2)}`;
}

export function buildSynthesisPrompt(
  ticker: string,
  lensOutputs: Record<string, string>,
  failedLenses: string[]
): string {
  const sections = Object.entries(lensOutputs)
    .map(([key, text]) => `## ${key.toUpperCase()} ANALYST SAID:\n${text}`)
    .join("\n\n");
  const gaps = failedLenses.length
    ? `\n\nNote: the following analyses were unavailable for this run and must be acknowledged in the relevant report sections: ${failedLenses.map((k) => `${k} lens unavailable`).join("; ")}.`
    : "";

  return `You are the lead editor of a research panel. Four specialist analyses of ${ticker} are below. Merge them into ONE markdown research report for a beginner investor.${gaps}

The report MUST use exactly these markdown sections, in this order:
# ${ticker} Research Report
## TL;DR
(max 5 bullets)
## The Business
## Financial Health
## Valuation
## Bull Case
## Bear Case
## Red Flags
## What Would Need to Be True
(what facts would need to hold for owning this to make sense — frame as research questions, NOT advice)
## Glossary
(every finance term used above, one-line beginner definitions)

Rules: keep every concrete figure the analysts cited; resolve contradictions by presenting both views; explain terms for a beginner; never give a buy/sell/hold recommendation.

${sections}`;
}
